name: brew test-bot
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test-bot:
    strategy:
      matrix:
        os:
          # Run only on macOS because this tap contains only a cask,
          # and casks are macOS apps.
          # - ubuntu-latest
          - macos-latest
          - macos-15-intel
    runs-on: ${{ matrix.os }}
    permissions:
      actions: read
      checks: read
      contents: read
      pull-requests: read
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Homebrew Bundler RubyGems
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ matrix.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ matrix.os }}-rubygems-

      - name: Print brew config excerpts
        run: brew config | awk 'BEGIN{printf("%s\n", "brew config excerpts:")} /^macOS|Linux|Windows|CPU|HOMEBREW_VERSION|Last commit:/ {print}'

      - run: brew test-bot --only-cleanup-before

      - run: brew test-bot --only-setup

      # Run cask/audit steps only on macOS. This tap contains only a Cask and
      # auditing it on Linux (or with --os=all) can cause "invalid 'sha256' value: nil".
      # Keep other steps running on all matrix runners.
      - run: brew test-bot --only-tap-syntax
        if: ${{ runner.os == 'macOS' }}

      # Skipping formula-related steps for cask-only tap.
      # Formula tests and bottle uploads are not applicable to casks.
      # - run: brew test-bot --only-formulae
      #   if: github.event_name == 'pull_request'

      # - name: Upload bottles as artifact
      #   if: always() && github.event_name == 'pull_request'
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: bottles
      #     path: '*.bottle.*'
